version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env

  adminer:
    container_name: adminer
    image: adminer
    restart: "always"
    ports:
      - 8080:8080
    depends_on:
      - db
