"""init

Revision ID: 0317e6097ed3
Revises: a78dcf82dd17
Create Date: 2023-12-19 23:54:46.633348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0317e6097ed3'
down_revision = 'a78dcf82dd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('age', sa.Unicode(length=255), nullable=False),
    sa.Column('has_disease', sa.Boolean(), nullable=True),
    sa.Column('certanity', sa.Unicode(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    # ### end Alembic commands ###
